# Generated by Django 3.2.18 on 2023-04-05 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bizlead', '0002_rename_contact_bizlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demostatus', models.CharField(blank=True, choices=[('DONE', 'DONE'), ('PENDING', 'PENDING')], max_length=30)),
                ('demodate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('Attendees', models.TextField(blank=True)),
                ('meeting', models.CharField(blank=True, choices=[('PHYSICAL', 'PHYSICAL'), ('VIRTUAL', 'VIRTUAL')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('demo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bizlead.bizlead')),
            ],
        ),
    ]
