# Generated by Django 3.2.18 on 2023-04-05 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bizlead', '0004_auto_20230405_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='assessmentdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='demodate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='reportdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
