# Generated by Django 3.2.18 on 2023-04-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizlead', '0007_auto_20230406_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demostatus', models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING')], default='PENDING', max_length=30)),
                ('demodate', models.DateField(blank=True, default=None, null=True)),
                ('Attendees', models.TextField(blank=True)),
                ('meeting', models.CharField(blank=True, choices=[('PHYSICAL', 'PHYSICAL'), ('VIRTUAL', 'VIRTUAL')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('demo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bizlead.bizlead')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentdate', models.DateField(blank=True, default=None, null=True)),
                ('report', models.FileField(blank=True, upload_to='documents/')),
                ('reportdate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supportingdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.FileField(blank=True, upload_to='documents/')),
                ('facility_license', models.FileField(blank=True, upload_to='documents/')),
                ('krapin', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Conversion',
        ),
    ]
