# Generated by Django 3.2.18 on 2023-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlead', '0009_auto_20230419_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdoc',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='demo',
            name='assessmentdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='expression',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='facility_license',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='krapin',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='report',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='demo',
            name='reportdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='SiteAssessment',
        ),
        migrations.DeleteModel(
            name='Supportingdoc',
        ),
    ]
