# Generated by Django 3.2.18 on 2023-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('clientname', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('project_cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
