# Generated by Django 3.2.18 on 2023-03-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230316_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_amt', models.PositiveIntegerField(default=0, unique=True)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('total_invoice', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amt_paid', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bill')),
                ('invoice', models.ForeignKey(db_column='invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.invoice', to_field='invoice_amt')),
            ],
        ),
    ]
