# Generated by Django 3.2.18 on 2023-03-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230321_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_amt', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
                ('tax', models.PositiveIntegerField(default=0)),
                ('total_invoice', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bill')),
            ],
        ),
    ]
