# Generated by Django 3.2.18 on 2023-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230321_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_invoice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='invoice',
        ),
        migrations.AddField(
            model_name='receipts',
            name='invoice',
            field=models.ManyToManyField(to='accounts.Invoice'),
        ),
    ]
