# Generated by Django 3.2.18 on 2023-03-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230321_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_facility', to='accounts.invoice'),
        ),
        migrations.RemoveField(
            model_name='receipts',
            name='invoice',
        ),
        migrations.AddField(
            model_name='receipts',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_total_invoice', to='accounts.invoice'),
        ),
    ]
