# Generated by Django 3.2.18 on 2023-03-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230321_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipts',
            old_name='transaction',
            new_name='transaction_date',
        ),
    ]
