# Generated by Django 3.2.18 on 2023-03-22 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='golive_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
