# Generated by Django 3.2.18 on 2023-03-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_golive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_date',
        ),
    ]
