# Generated by Django 3.2.18 on 2023-03-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_account_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
