# Generated by Django 3.2.18 on 2023-03-27 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
