# Generated by Django 3.2.18 on 2023-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20230327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='payment_mode',
            field=models.CharField(choices=[('Mobile_Banking ', 'Mpesa'), ('Bank_Transaction', 'Cheque'), ('Bank_Payment', 'Bank Payment')], default='Mpesa', max_length=20),
        ),
    ]
