# Generated by Django 3.2.18 on 2023-03-29 07:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_receipts_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='license_due',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='no_of_days',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
