# Generated by Django 3.2.18 on 2023-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20230329_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='no_of_days',
            field=models.DurationField(),
        ),
    ]
