# Generated by Django 3.2.18 on 2023-03-29 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_account_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
