# Generated by Django 3.2.18 on 2023-03-29 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_receipts_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
