# Generated by Django 3.2.18 on 2023-03-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_receipts_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='facility_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receipts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bill'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
