# Generated by Django 3.2.18 on 2023-03-29 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20230329_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='no_of_days',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
