# Generated by Django 3.2.18 on 2023-03-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20230329_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='payment_mode',
            field=models.CharField(choices=[('MPESA ', 'Mpesa'), ('Cheque', 'Cheque'), ('Banking', 'Bank Payment')], default='Mpesa', max_length=20),
        ),
    ]
