# Generated by Django 3.2.18 on 2023-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_receipts_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='no_of_days',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
