# Generated by Django 3.2.18 on 2023-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_account_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='golive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
