# Generated by Django 3.2.18 on 2023-03-22 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.CharField(choices=[('Patient_Register', 'PATIENT REGISTER'), ('Nurse', 'NURSE'), ('Doctor', 'DOCTOR'), ('Laboratory', 'LABORATORY'), ('Radiography', 'RADIOGRAPHY'), ('Inpatient', 'INPATIENT'), ('Pharmacy', 'PHARMACY'), ('Cashier', 'CASHIER'), ('Inventory', 'INVENTORY'), ('Finance', 'FINANCE'), ('Human_Resource', 'HUMAN RESOURCE'), ('System_Admin', 'SYSTEM ADMIN')], default='Mpesa', max_length=20)),
                ('problem', models.CharField(max_length=20)),
                ('solution', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Incomplete ', 'PENDING'), ('Complete', 'DONE')], default='Mpesa', max_length=20)),
                ('completiondate', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receipts')),
            ],
        ),
    ]
