# Generated by Django 3.2.18 on 2023-03-22 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='completiondate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='support',
            name='logdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
