# Generated by Django 3.2.18 on 2023-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20230322_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='support',
        ),
    ]
