# Generated by Django 3.2.18 on 2023-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='module',
            field=models.CharField(choices=[('Patient_Register', 'PATIENT REGISTER'), ('Nurse', 'NURSE'), ('Doctor', 'DOCTOR'), ('Laboratory', 'LABORATORY'), ('Radiography', 'RADIOGRAPHY'), ('Inpatient', 'INPATIENT'), ('Pharmacy', 'PHARMACY'), ('Cashier', 'CASHIER'), ('Inventory', 'INVENTORY'), ('Finance', 'FINANCE'), ('Human_Resource', 'HUMAN RESOURCE'), ('System_Admin', 'SYSTEM ADMIN')], default='Mpesa', max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='problem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
