# Generated by Django 3.2.18 on 2023-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20230322_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='module',
            field=models.CharField(choices=[('PATIENT REGISTER', 'PATIENT REGISTER'), ('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('LABORATORY', 'LABORATORY'), ('RADIOGRAPHY', 'RADIOGRAPHY'), ('INPATIENT', 'INPATIENT'), ('PHARMACY', 'PHARMACY'), ('CASHIER', 'CASHIER'), ('INVENTORY', 'INVENTORY'), ('FINANCE', 'FINANCE'), ('HUMAN RESOURCE', 'HUMAN RESOURCE'), ('SYSTEM ADMIN', 'SYSTEM ADMIN')], default='PATIENT REGISTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('PENDING ', 'PENDING'), ('DONE', 'DONE')], default='DONE', max_length=20),
        ),
    ]
