# Generated by Django 3.2.18 on 2023-03-23 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account'),
        ('support', '0008_courtesy'),
    ]

    operations = [
        migrations.CreateModel(
            name='bimonthly',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logdate', models.DateField(default=django.utils.timezone.now)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.receipts')),
            ],
        ),
    ]
