# Generated by Django 3.2.18 on 2023-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_support_completiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='completiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
