# Generated by Django 3.2.18 on 2023-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_auto_20230420_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='completiondate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='support',
            name='logdate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='support',
            name='module',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='solution',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
