# Generated by Django 3.2.18 on 2023-04-20 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_auto_20230420_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='completiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='logdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='support',
            name='module',
            field=models.CharField(choices=[('PATIENT REGISTER', 'PATIENT REGISTER'), ('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('LABORATORY', 'LABORATORY'), ('RADIOGRAPHY', 'RADIOGRAPHY'), ('INPATIENT', 'INPATIENT'), ('PHARMACY', 'PHARMACY'), ('CASHIER', 'CASHIER'), ('INVENTORY', 'INVENTORY'), ('FINANCE', 'FINANCE'), ('HUMAN RESOURCE', 'HUMAN RESOURCE'), ('SYSTEM ADMIN', 'SYSTEM ADMIN')], default='PATIENT REGISTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='support',
            name='problem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('PENDING ', 'PENDING'), ('DONE', 'DONE')], default='DONE', max_length=20),
        ),
    ]
