# Generated by Django 3.2.18 on 2023-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_auto_20230420_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
